create table products (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    normalized_name varchar(120) not null unique,
    created_at timestamp with time zone not null
);

create table stock_entries (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products (id),
    initial_quantity integer not null check (initial_quantity > 0),
    available_quantity integer not null check (available_quantity >= 0),
    expiration_date date not null,
    created_at timestamp with time zone not null
);

create index idx_stock_entries_active_expiration
    on stock_entries (expiration_date, created_at)
    where available_quantity > 0;

create table stock_movements (
    id bigint generated by default as identity primary key,
    stock_entry_id bigint not null references stock_entries (id),
    movement_type varchar(20) not null check (movement_type in ('ENTRY', 'WITHDRAWAL')),
    quantity integer not null check (quantity > 0),
    reason varchar(30),
    created_at timestamp with time zone not null
);

create index idx_stock_movements_created_at
    on stock_movements (created_at desc);
