spring.application.name=vence-facil-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vence_facil}
spring.datasource.username=${DB_USERNAME:vence_facil}
spring.datasource.password=${DB_PASSWORD:vence_facil_local}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.mvc.problemdetails.enabled=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

server.port=${SERVER_PORT:8080}
server.shutdown=graceful

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true

info.app.name=Vence Facil API
info.app.description=API para controle simples de validade de produtos
info.app.version=@project.version@
